## Load Numpy

In [22]:
import numpy as np

## The Basics

In [23]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [24]:
b = np.array([[7.0,8.0,9.0],[6.0,5.0,4.0]])
print(b)

[[7. 8. 9.]
 [6. 5. 4.]]


* Get Dimension

In [25]:
a.ndim

1

* Get shape

In [26]:
b.shape

(2, 3)

* Get type

In [27]:
a.dtype
#b.dtype

dtype('int64')

* Get size

In [28]:
a.size
b.size #total number of items in array

6

* Get item size

In [29]:
a.itemsize #Size of a single item in bytes

8

# Accessing/Changing specific elements, rows, columns, etc

In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


* Get specific element

In [31]:
a[1,5]

np.int64(13)

* Get specific row

In [33]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

* Get specific column

In [34]:
a[:,-1] #get the last column

array([ 7, 14])

* Getting a little more fancy [startindex:endindex:stepsize]

In [45]:
a[1,:7:2]

array([ 8, 10, 12, 14])

* update data item

In [48]:
a[0,0]=12
print(a)
a[:,-1]=[14,15]
print(a)

[[12  2  3  4  5  6 14]
 [ 8  9 10 11 12 13 15]]
[[12  2  3  4  5  6 14]
 [ 8  9 10 11 12 13 15]]


# 3d Example

In [50]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]);
print(c);

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


* Get specific element (work outside in)

In [56]:
c[0,0,2]

np.int64(3)

* Replace

In [58]:
c[:,1,:] =[[13,14,15],[21,22,23]]

In [59]:
print(c)

[[[ 1  2  3]
  [13 14 15]]

 [[ 7  8  9]
  [21 22 23]]]


# Inicializing Different types of Arrays

* All zeros os matrix

In [61]:
print(np.zeros(5))
print(np.zeros((2,2))) #parameter shape

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]


* All 1s matrix

In [62]:
print(np.ones((2,3),dtype="int16"))

[[1 1 1]
 [1 1 1]]


* Any number

In [64]:
print(np.full((2,2),99))
print(np.full_like(b,8))

[[99 99]
 [99 99]]
[[8. 8. 8.]
 [8. 8. 8.]]


* Random decimals numbers

In [66]:
np.random.rand(2,4)
np.random.random_sample(c.shape)

array([[[0.93952832, 0.51712402, 0.27129229],
        [0.24645167, 0.57019725, 0.89115429]],

       [[0.27089786, 0.56944503, 0.40273998],
        [0.95882278, 0.06342088, 0.81217255]]])

* Random integer

In [73]:
np.random.randint(7,10,size=(2,2))

array([[9, 8],
       [7, 9]])

* The identity matriz

In [74]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* Repeat an array

In [76]:
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Inicializing an array

In [85]:
output =  np.ones((5,5))
output[1:-1,1:-1] = np.zeros(output[1:-1,1:-1].shape)
output[2,2]=9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!

In [87]:
original =  np.array([1,2,3])
#original = new it's make a pointing new to original
new =  np.copy(original) #this makes a real copy of the entire array
print(original)

[1 2 3]


# Mathematics

In [88]:
a = np.array([1,2,3,4,5])

In [92]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [91]:
b=np.array([1,1,1,1,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [97]:
# Create an array
arr = np.array([[1, 0, 3],
                [0, 0, 0],
                [7, 0, 9]])

# Use np.any along axis=1 (rows) to find rows with at least one non-zero element
mask = np.any(arr != 0, axis=0)  # Boolean mask: [True, False, True]

# Use the boolean mask to index the original array
result = arr[mask]

print(result)

[[1 0 3]
 [7 0 9]]


In [99]:
# Create an array
arr = np.array([[1, 2, 3],
                [0, 0, 0],
                [7, 8, 9]])

# Use np.all along axis=1 (rows) to find rows where all elements are non-zero
mask = np.all(arr != 0, axis=0)  # Boolean mask: [True, False, True]

# Use the boolean mask to index the original array
result = arr[mask]

print(result)


[]
