## Importacion de biblioteca

In [3]:
import numpy as np

## Creacion de arrays

In [6]:
lista = [1,2,3,4,5]
array =  np.array(lista)
print(array)

[1 2 3 4 5]


## Array de unos y ceros

In [10]:
ceros = np.zeros((3,2)) # se le puede pasar una tupla para representar la matriz a construir
print(ceros)
unos = np.ones((3,4))
print(unos)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Rangos

In [11]:
rangos = np.arange(2,12,2) #toma de primer parametro el inicio,fin y salto
print(rangos)

[ 2  4  6  8 10]


## Numeros aleatorios

In [29]:
numerosAleatorios = np.random.random((3,3)) #genera numeros aleatorios decimales principalmente
print(numerosAleatorios)
numerosAleatorios =  np.random.randint(2,10,(3,3),'int')
print(numerosAleatorios)

[[0.68365458 0.93280314 0.01673681]
 [0.11744406 0.8506283  0.48312324]
 [0.40823915 0.89227042 0.53291921]]
[[7 9 4]
 [2 7 3]
 [8 2 8]]


In [30]:
## Propiedades y Métodos de los Arrays

In [41]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape) #cantidad de filas y columnas
print(array.size)# cantidad de valores del array
print(array.ndim) #cantidad de dimensiones del array
reshape = array.reshape((3,2))#cambia filas por columnas
print(reshape)
flatter =  array.flatten()
print(flatter)#convierte un array multidimensional a un array unidimensional

(2, 3)
6
2
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


## Operaciones Básicas con Arrays

In [42]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

suma = array1 + array2
resta = array1 - array2

print("Suma:", suma)
print("Resta:", resta)

Suma: [5 7 9]
Resta: [-3 -3 -3]


# Multiplicación y División

In [43]:
multiplicacion = array1 * array2
division = array1 / array2

print("Multiplicación:", multiplicacion)
print("División:", division)

Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


# Operaciones universales. (Aplicados a cada elemento de la matriz)

In [44]:
array = np.array([1, 2, 3])

sqrt = np.sqrt(array)
log = np.log(array)

print("Raíz cuadrada:", sqrt)
print("Logaritmo natural:", log)

Raíz cuadrada: [1.         1.41421356 1.73205081]
Logaritmo natural: [0.         0.69314718 1.09861229]


#Indexación y Slicing de Arrays

In [47]:
array = np.array([1, 2, 3, 4, 5])
print(array[0])  # Primer elemento
print(array[-1])  # Último elemento
#slicing
print(array[1:4])  # Elementos del índice 1 al 3
print(array[:3])  # Primeros tres elementos
print(array[2:])  # Elementos desde el índice 2 hasta el final

1
5
[2 3 4]
[1 2 3]
[3 4 5]


# Indexación y Slicing en Arrays Multidimensionales

In [48]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array[1, 2])  # Elemento en la fila 1, columna 2
print(array[0:2, 1:3])  # Subarray desde fila 0 a 1 y columna 1 a 2

6
[[2 3]
 [5 6]]


# Agregaciones y Estadísticas

In [49]:
array = np.array([1, 2, 3, 4, 5])
print(np.sum(array))  # Suma de todos los elementos
print(np.prod(array))  # Producto de todos los elementos

15
120


In [50]:
print(np.mean(array))  # Media (promedio)
print(np.median(array))  # Mediana
print(np.std(array))  # Desviación estándar
print(np.var(array))  # Varianza

3.0
3.0
1.4142135623730951
2.0


In [51]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(array, axis=0))  # Suma a lo largo de las columnas
print(np.sum(array, axis=1))  # Suma a lo largo de las filas

[12 15 18]
[ 6 15 24]
